# frozen_string_literal: true

source 'https://rubygems.org'

gem 'awesome_print'
gem 'pry-byebug'
gem 'wicked_pdf'

gem 'sorbet', group: :development
gem 'sorbet-runtime'
gem 'tapioca', require: false, group: :development
